image:
  - Visual Studio 2019
platform:
  - Any CPU
configuration:
  - Debug
  - Release
install:
  - git submodule update --init --recursive
build:
  project: BetterDP.sln
before_build:
  - nuget restore
